---
name: "User Password Reset"
guid: "d8c01d3b-9b3f-4f4c-a0f3-8d3a7a8b4c11"
version: "0.9.0.0"
targetAbi: "10.9.11.0"
framework: "net9.0"
overview: "Admin plugin to reset user passwords from the dashboard"
description: >
  A simple but powerful Jellyfin admin plugin that allows administrators 
  to list users and reset their passwords directly from the web dashboard.
  Features instant password generation, clipboard support, and native UI integration.
category: "General"
owner: "HovigCreates"
artifacts:
- "Jellyfin.Plugin.Template.dll"
changelog: >
  Initial release v0.9.0
  - User list with admin/user badges
  - One-click password reset with secure random generation
  - Clipboard copy functionality
  - Native Jellyfin UI integration
